apiVersion: ecsctl/v1
kind: Service
metadata:
  name: openab-chaodu
  cluster: openab
spec:
  image: ghcr.io/openabdev/openab:beta
  cpu: '2048'
  memory: '4096'
  arch: X86_64
  capacity: FARGATE_SPOT
  desiredCount: 1
  execEnabled: true
  env:
    GHPOOL_URL: http://ghpool.openab.local:8080
    STATE_BUCKET: openab-state-pahud
    OPENAB_BACKEND_AGENT: openab
    GITHUB_API_URL: http://ghpool.openab.local:8080
    OPENAB_AGENT_NAME: chaodu
  secrets:
    STT_API_KEY: 'arn:aws:secretsmanager:us-east-1:903779448426:secret:oab-dHVVk4:STT_API_KEY::'
    DISCORD_BOT_TOKEN: 'arn:aws:secretsmanager:us-east-1:903779448426:secret:oab-dHVVk4:CHAODU_BOT_TOKEN::'
  logGroup: /ecs/openab
  executionRoleArn: arn:aws:iam::903779448426:role/openab-ecs-execution-role
  taskRoleArn: arn:aws:iam::903779448426:role/openab-ecs-task-chaodu
  subnets:
  - subnet-0564da5939b9f37e8
  securityGroups:
  - sg-0bc22bce7e98d79b0
  assignPublicIp: true
  containerName: openab
  port: 0
  command:
  - sh
  - -c
  - exec /usr/local/bin/openab run -c https://gist.githubusercontent.com/chaodu-agent/8e89b7b22f1552b2f3da09a714fd3f4b/raw/config-chaodu.toml
